spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:

          - id: notification-service
            uri: ${NOTIFICATION_SERVICE_WS:ws://notification-service:8080}
            predicates:
              - Path=/ws/notifications**
            filters:
              - PreserveHostHeader

          - id: user-service
            uri: ${USER_SERVICE_URL:http://user-service:8080}
            predicates:
              - Path=/users, /users/**
            filters:
              - StripPrefix=1

          - id: book-service
            uri: ${BOOK_SERVICE_URL:http://book-service:8080}
            predicates:
              - Path=/books, /books/**
            filters:
              - StripPrefix=1
 
          - id: loan-service
            uri: ${LOAN_SERVICE_URL:http://loan-service:8080}
            predicates:
              - Path=/loans, /loans/**
            filters:
              - StripPrefix=1
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/library-microservices/protocol/openid-connect/certs

    user:
      name: none
      password: none

  reactor:
    context-propagation: auto

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    export:
      zipkin:
        endpoint: ${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}