spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:

          - id: auth-service
            uri: http://user-service:8080
            predicates:
              - Path=/auth/**
              
          - id: user-service
            uri: http://user-service:8080
            predicates:
              - Path=/users, /users/**
            filters:
              - StripPrefix=1

          - id: book-service
            uri: http://book-service:8080
            predicates:
              - Path=/books, /books/**
            filters:
              - StripPrefix=1

          - id: loan-service
            uri: http://loan-service:8080
            predicates:
              - Path=/loans, /loans/**
            filters:
              - StripPrefix=1

  security:
    jwt:
      enabled: true
      issuer: user-service
      secret: ${JWT_SECRET:d6ISU26dwuewuDCpql4e0kJkCNM5WmrggGtnoqQ35VU=}
      access-token-expiration-minutes: 15
      refresh-token-expiration-days: 7

    user:
      name: none
      password: none