services:

  zipkin:
    profiles: ["dev"]
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"

  zipkin-gherkin:
    profiles: ["gherkin"]
    image: openzipkin/zipkin:latest
    container_name: zipkin-gherkin
    ports:
      - "9412:9411"
      
  postgres-keycloak:
    image: postgres:15
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - "5433:5432"
    volumes:
      - keycloak_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: 
      - start-dev
      - --http-enabled=true
      - --hostname-strict=false
      - --import-realm

    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-keycloak:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
   
    ports:
      - "8084:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./keycloak/import:/opt/keycloak/data/import
      - ./keycloak/themes:/opt/keycloak/themes
    depends_on:
      postgres-keycloak:
        condition: service_healthy

  rabbitmq:
    profiles: ["dev"]
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json  
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 10
  
  rabbitmq-gherkin:
    profiles: ["gherkin"]
    image: rabbitmq:3-management
    container_name: rabbitmq-gherkin
    ports:
      - "5673:5672"
      - "15673:15672"
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json  
    tmpfs:    
      - /var/lib/rabbitmq 
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 10

  mysql-book:
    profiles: ["dev"]
    image: mysql:8
    container_name: mysql-book
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: book_db
      MYSQL_USER: libraryApp
      MYSQL_PASSWORD: libraryAppTest!
    ports:
      - "3307:3306"
    volumes:
      - mysql_book_data:/var/lib/mysql
      - ./mysql-book:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10

  mysql-loan:
    profiles: ["dev"]
    image: mysql:8
    container_name: mysql-loan
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: loan_db
      MYSQL_USER: libraryApp
      MYSQL_PASSWORD: libraryAppTest!
    ports:
      - "3308:3306"
    volumes:
      - mysql_loan_data:/var/lib/mysql
      - ./mysql-loan:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10

  mysql-user:
    profiles: ["dev"]
    image: mysql:8
    container_name: mysql-user
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_db
      MYSQL_USER: libraryApp
      MYSQL_PASSWORD: libraryAppTest!
    ports:
      - "3309:3306"
    volumes:
      - mysql_user_data:/var/lib/mysql
      - ./mysql-user/init-dev:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10

  mysql-book-gherkin:
    profiles: ["gherkin"]
    image: mysql:8
    container_name: mysql-book-gherkin
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: book_test_db
      MYSQL_USER: libraryApp
      MYSQL_PASSWORD: libraryAppTest!
    ports:
      - "3317:3306"
    tmpfs:
      - /var/lib/mysql
    volumes:
      - ./mysql-book:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10

  mysql-loan-gherkin:
    profiles: ["gherkin"]
    image: mysql:8
    container_name: mysql-loan-gherkin
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: loan_test_db
      MYSQL_USER: libraryApp
      MYSQL_PASSWORD: libraryAppTest!
    ports:
      - "3318:3306"
    tmpfs:
      - /var/lib/mysql
    volumes:
      - ./mysql-loan:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10

  mysql-user-gherkin:
    profiles: ["gherkin"]
    image: mysql:8
    container_name: mysql-user-gherkin
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_test_db
      MYSQL_USER: libraryApp
      MYSQL_PASSWORD: libraryAppTest!
    ports:
      - "3319:3306"
    tmpfs:
      - /var/lib/mysql
    volumes:
      - ./mysql-user/init-test:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10
      
  book-service:
    profiles: ["dev"]
    image: book-service:dev
    container_name: book-service
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-book:3306/book_db?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: libraryApp
      SPRING_DATASOURCE_PASSWORD: libraryAppTest!
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/library-microservices/protocol/openid-connect/certs
      ZIPKIN_ENDPOINT: http://zipkin:9411/api/v2/spans
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      mysql-book:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      keycloak:
        condition: service_started
      zipkin:
        condition: service_started
      
  loan-service:
    profiles: ["dev"]
    image: loan-service:dev
    container_name: loan-service
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-loan:3306/loan_db?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: libraryApp
      SPRING_DATASOURCE_PASSWORD: libraryAppTest!
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/library-microservices/protocol/openid-connect/certs
      ZIPKIN_ENDPOINT: http://zipkin:9411/api/v2/spans
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      mysql-loan:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      keycloak:
        condition: service_started
      zipkin:
        condition: service_started

  user-service:
    profiles: ["dev"]
    image: user-service:dev
    container_name: user-service
    ports:
      - "8083:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-user:3306/user_db?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: libraryApp
      SPRING_DATASOURCE_PASSWORD: libraryAppTest!
      KEYCLOAK_BASE_URL: http://keycloak:8080
      KEYCLOAK_ADMIN_REALM: library-microservices
      KEYCLOAK_REALM: library-microservices
      KEYCLOAK_ADMIN_CLIENT_ID: user-service-admin
      KEYCLOAK_ADMIN_CLIENT_SECRET: CtxSOiaFcaGv8PjMnOVig7jEPUC2X6mm
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/library-microservices/protocol/openid-connect/certs
      ZIPKIN_ENDPOINT: http://zipkin:9411/api/v2/spans
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      mysql-user:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      keycloak:
        condition: service_started
      zipkin:
        condition: service_started
        
  notification-service:
    profiles: ["dev"]
    image: notification-service:dev
    container_name: notification-service
    ports:
      - "8085:8080"
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/library-microservices/protocol/openid-connect/certs
      ZIPKIN_ENDPOINT: http://zipkin:9411/api/v2/spans
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      rabbitmq:
        condition: service_started
      keycloak:
        condition: service_started
      zipkin:
        condition: service_started
        
  book-service-gherkin:
    profiles: ["gherkin"]
    image: book-service:dev
    container_name: book-service-gherkin
    ports:
      - "9081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-book-gherkin:3306/book_test_db?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: libraryApp
      SPRING_DATASOURCE_PASSWORD: libraryAppTest!
      SPRING_RABBITMQ_HOST: rabbitmq-gherkin
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/library-microservices-test/protocol/openid-connect/certs
      ZIPKIN_ENDPOINT: http://zipkin-gherkin:9411/api/v2/spans
      SPRING_PROFILES_ACTIVE: gherkin
      APP_TEST_MODE: true
    depends_on:
      mysql-book-gherkin:
        condition: service_healthy
      rabbitmq-gherkin:
        condition: service_started
      keycloak:
        condition: service_started
      zipkin-gherkin:
        condition: service_started
      
  loan-service-gherkin:
    profiles: ["gherkin"]
    image: loan-service:dev
    container_name: loan-service-gherkin
    ports:
      - "9082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-loan-gherkin:3306/loan_test_db?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: libraryApp
      SPRING_DATASOURCE_PASSWORD: libraryAppTest!
      SPRING_RABBITMQ_HOST: rabbitmq-gherkin
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/library-microservices-test/protocol/openid-connect/certs
      ZIPKIN_ENDPOINT: http://zipkin-gherkin:9411/api/v2/spans
      SPRING_PROFILES_ACTIVE: gherkin
      APP_TEST_MODE: true
    depends_on:
      mysql-loan-gherkin:
        condition: service_healthy
      rabbitmq-gherkin:
        condition: service_started
      keycloak:
        condition: service_started
      zipkin-gherkin:
        condition: service_started

  user-service-gherkin:
    profiles: ["gherkin"]
    image: user-service:dev
    container_name: user-service-gherkin
    ports:
      - "9083:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-user-gherkin:3306/user_test_db?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: libraryApp
      SPRING_DATASOURCE_PASSWORD: libraryAppTest!
      KEYCLOAK_BASE_URL: http://keycloak:8080
      KEYCLOAK_ADMIN_REALM: library-microservices-test
      KEYCLOAK_REALM: library-microservices-test
      KEYCLOAK_ADMIN_CLIENT_ID: user-service-admin
      KEYCLOAK_ADMIN_CLIENT_SECRET: CtxSOiaFcaGv8PjMnOVig7jEPUC2X6mm
      SPRING_RABBITMQ_HOST: rabbitmq-gherkin
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/library-microservices-test/protocol/openid-connect/certs
      ZIPKIN_ENDPOINT: http://zipkin-gherkin:9411/api/v2/spans
      SPRING_PROFILES_ACTIVE: gherkin
      APP_TEST_MODE: true
    depends_on:
      mysql-user-gherkin:
        condition: service_healthy
      rabbitmq-gherkin:
        condition: service_started
      keycloak:
        condition: service_started
      zipkin-gherkin:
        condition: service_started
        
  notification-service-gherkin:
    profiles: ["gherkin"]
    image: notification-service:dev
    container_name: notification-service-gherkin
    ports:
      - "9085:8080"
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq-gherkin
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/library-microservices-test/protocol/openid-connect/certs
      ZIPKIN_ENDPOINT: http://zipkin-gherkin:9411/api/v2/spans
      SPRING_PROFILES_ACTIVE: gherkin
      APP_TEST_MODE: true
    depends_on:
      rabbitmq-gherkin:
        condition: service_started
      keycloak:
        condition: service_started
      zipkin-gherkin:
        condition: service_started
        
  api-gateway:
    profiles: ["dev"]
    image: api-gateway:dev
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      NOTIFICATION_SERVICE_WS: ws://notification-service:8080
      BOOK_SERVICE_URL: http://book-service:8080
      LOAN_SERVICE_URL: http://loan-service:8080
      USER_SERVICE_URL: http://user-service:8080
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/library-microservices/protocol/openid-connect/certs
      ZIPKIN_ENDPOINT: http://zipkin:9411/api/v2/spans
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      book-service:
        condition: service_started
      loan-service:
        condition: service_started
      user-service:
        condition: service_started
      keycloak:
        condition: service_started
      zipkin:
        condition: service_started

  api-gateway-gherkin:
    profiles: ["gherkin"]
    image: api-gateway:dev
    container_name: api-gateway-gherkin
    ports:
      - "9080:8080"
    environment:
      NOTIFICATION_SERVICE_WS: ws://notification-service-gherkin:8080
      BOOK_SERVICE_URL: http://book-service-gherkin:8080
      LOAN_SERVICE_URL: http://loan-service-gherkin:8080
      USER_SERVICE_URL: http://user-service-gherkin:8080
      SPRING_RABBITMQ_HOST: rabbitmq-gherkin
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: http://keycloak:8080/realms/library-microservices-test/protocol/openid-connect/certs
      ZIPKIN_ENDPOINT: http://zipkin-gherkin:9411/api/v2/spans
      SPRING_PROFILES_ACTIVE: gherkin
      APP_TEST_MODE: true
    depends_on:
      book-service-gherkin:
        condition: service_started
      loan-service-gherkin:
        condition: service_started
      user-service-gherkin:
        condition: service_started
      keycloak:
        condition: service_started
      zipkin-gherkin:
        condition: service_started
        
volumes:
  rabbitmq_data:
  keycloak_db:
  keycloak_data:
  mysql_book_data:
  mysql_loan_data:
  mysql_user_data:
