spring:
  application:
    name: book-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/book_db}
    username: ${SPRING_DATASOURCE_USERNAME:libraryApp}
    password: ${SPRING_DATASOURCE_PASSWORD:libraryAppTest!}
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      maximumPoolSize: 10
      minimumIdle: 2
      initializationFailTimeout: 0
      connectionTimeout: 30000
      validationTimeout: 5000

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.type.json_format_mapper: mentoring.acomi.bookservice.infrastructure.persistence.configuration.Jackson3HibernateJsonFormatMapper

  security:
    user:
      name: none
      password: none
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/library-microservices

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: 5672
    username: libraryApp
    password: libraryAppTest!
    template:
      observation-enabled: true
    listener:
      simple:
        observation-enabled: true

  sql:
    init:
      continue-on-error: true

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0