spring:
  application:
    name: user-service    
    
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/user_db}
    username: ${SPRING_DATASOURCE_USERNAME:libraryApp}
    password: ${SPRING_DATASOURCE_PASSWORD:libraryAppTest!}
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      maximumPoolSize: 10
      minimumIdle: 2
      initializationFailTimeout: 0
      connectionTimeout: 30000
      validationTimeout: 5000

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.type.json_format_mapper: mentoring.acomi.loanservice.infrastructure.persistence.configuration.Jackson3HibernateJsonFormatMapper
      
  security:
    jwt:
      enabled: true
      issuer: user-service
      secret: ${JWT_SECRET:d6ISU26dwuewuDCpql4e0kJkCNM5WmrggGtnoqQ35VU=}
      access-token-expiration-minutes: 15
      refresh-token-expiration-days: 7
    user:
      name: none
      password: none

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: 5672
    username: libraryApp
    password: libraryAppTest!

  sql:
    init:
      continue-on-error: true